/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : pin_mux.h
**     Project     : KV10-Blink-Step-Bipolar2
**     Processor   : MKV10Z32VLF7
**     Component   : PinSettings
**     Version     : Component 1.2.0, Driver 1.4, CPU db: 3.00.000
**     Repository  : KSDK 1.2.0
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-06-29, 13:18, # CodeGen: 0
**     Abstract    :
**
**     Settings    :
**          Component name                                 : pin_mux
**          PinSettings IP Block                           : PinSettings
**          Processor                                      : MKV10Z32LF7_4SDK
**          Pin settings                                   : 
**            Routing                                      : 
**              Peripheral Type ADC                        : 
**                Custom name                              : ADC0
**                ADC0                                     : 
**                  ADC analog minus channel 0             : <Automatic>
**                  ADC analog minus channel 1             : <Automatic>
**                  ADC analog plus channel 0              : <Automatic>
**                  ADC analog plus channel 1              : <Automatic>
**                  ADC analog single-ended channel 0      : <Automatic>
**                  ADC analog single-ended channel 1      : <Automatic>
**                  ADC analog single-ended channel 2      : <Automatic>
**                  ADC analog single-ended channel 3      : <Automatic>
**                  ADC analog single-ended channel 8      : <Automatic>
**                  ADC analog single-ended channel 9      : <Automatic>
**                  ADC analog single-ended channel 10     : <Automatic>
**                  ADC analog single-ended channel 11     : <Automatic>
**                  ADC analog single-ended channel 4a     : <Automatic>
**                  ADC analog single-ended channel 5a     : <Automatic>
**                  ADC analog single-ended channel 6a     : <Automatic>
**                  ADC analog single-ended channel 7a     : <Automatic>
**                  ADC trigger A input                    : <Automatic>
**                  ADC trigger B input                    : <Automatic>
**                  Voltage reference high single-ended channel 29 plus channel 29: VDDA
**                  Voltage reference high single-ended channel 29 plus channel 29: VREFH
**                  Voltage reference low single-ended channel 30 minus channel 29: VREFL
**                  Voltage reference low single-ended channel 30 minus channel 29: VSSA
**                Bool_ADC0                                : yes
**                Custom name                              : ADC1
**                ADC1                                     : 
**                  ADC analog minus channel 1             : <Automatic>
**                  ADC analog minus channel 2             : <Automatic>
**                  ADC analog plus channel 1              : <Automatic>
**                  ADC analog plus channel 2              : <Automatic>
**                  ADC analog single-ended channel 0      : <Automatic>
**                  ADC analog single-ended channel 1      : <Automatic>
**                  ADC analog single-ended channel 2      : <Automatic>
**                  ADC analog single-ended channel 3      : <Automatic>
**                  ADC analog single-ended channel 8      : <Automatic>
**                  ADC analog single-ended channel 9      : <Automatic>
**                  ADC analog single-ended channel 10     : <Automatic>
**                  ADC analog single-ended channel 11     : <Automatic>
**                  ADC analog single-ended channel 4a     : <Automatic>
**                  ADC analog single-ended channel 5a     : <Automatic>
**                  ADC analog single-ended channel 6a     : <Automatic>
**                  ADC analog single-ended channel 7a     : <Automatic>
**                  ADC trigger A input                    : <Automatic>
**                  ADC trigger B input                    : <Automatic>
**                Bool_ADC1                                : yes
**              Peripheral Type BP                         : 
**              Peripheral Type CMP                        : 
**                Custom name                              : CMP0
**                CMP0                                     : 
**                  Comparator input 0                     : <Automatic>
**                  Comparator input 1                     : <Automatic>
**                  Comparator input 4                     : <Automatic>
**                  Comparator input 5                     : <Automatic>
**                  Comparator output                      : <Automatic>
**                Bool_CMP0                                : yes
**                Custom name                              : CMP1
**                CMP1                                     : 
**                  Comparator input 0                     : <Automatic>
**                  Comparator input 1                     : <Automatic>
**                  Comparator input 4                     : <Automatic>
**                  Comparator input 5                     : <Automatic>
**                  Comparator output                      : <Automatic>
**                Bool_CMP1                                : yes
**              Peripheral Type CRC                        : 
**                Custom name                              : CRC
**              Peripheral Type CoreDebug                  : 
**                Custom name                              : CoreDebug
**                CoreDebug                                : 
**                  SWD Serial Wire Clock                  : <Automatic>
**                  SWD Serial wire debug data input output: <Automatic>
**                Bool_CoreDebug                           : yes
**              Peripheral Type DAC                        : 
**                Custom name                              : DAC0
**                DAC0                                     : 
**                  DAC output                             : <Automatic>
**                Bool_DAC0                                : yes
**              Peripheral Type DMA                        : 
**                Custom name                              : DMA
**              Peripheral Type DMAMUX                     : 
**                Custom name                              : DMAMUX
**              Peripheral Type DWT                        : 
**              Peripheral Type EWM                        : 
**                Custom name                              : EWM
**                EWM                                      : 
**                  EWM input                              : <Automatic>
**                  EWM output                             : <Automatic>
**                Bool_EWM                                 : yes
**              Peripheral Type FGPIO                      : 
**              Peripheral Type FTFA                       : 
**                Custom name                              : FTFA
**              Peripheral Type FTM                        : 
**                Custom name                              : FTM0
**                FTM0                                     : 
**                  FTM channel 0                          : <Automatic>
**                  Direction                              : <Automatic>
**                  FTM channel 1                          : <Automatic>
**                  Direction                              : <Automatic>
**                  FTM channel 2                          : <Automatic>
**                  Direction                              : <Automatic>
**                  FTM channel 3                          : <Automatic>
**                  Direction                              : <Automatic>
**                  FTM channel 4                          : <Automatic>
**                  Direction                              : <Automatic>
**                  FTM channel 5                          : <Automatic>
**                  Direction                              : <Automatic>
**                  FTM external clock input               : <Automatic>
**                  FTM fault input 0                      : <Automatic>
**                  FTM fault input 1                      : <Automatic>
**                  FTM fault input 2                      : <Automatic>
**                  FTM fault input 3                      : <Automatic>
**                  FTM trigger input 0                    : <Automatic>
**                  FTM trigger input 1                    : <Automatic>
**                  FTM trigger input 2                    : <Automatic>
**                Bool_FTM0                                : yes
**                Custom name                              : FTM1
**                FTM1                                     : 
**                  FTM channel 0                          : <Automatic>
**                  Direction                              : <Automatic>
**                  FTM channel 1                          : <Automatic>
**                  Direction                              : <Automatic>
**                  FTM external clock input               : <Automatic>
**                  FTM fault input 0                      : <Automatic>
**                  FTM quadrature decoder phase A input   : <Automatic>
**                  FTM quadrature decoder phase B input   : <Automatic>
**                  FTM trigger input 0                    : <Automatic>
**                  FTM trigger input 1                    : <Automatic>
**                  FTM trigger input 2                    : <Automatic>
**                Bool_FTM1                                : yes
**                Custom name                              : FTM2
**                FTM2                                     : 
**                  FTM channel 0                          : <Automatic>
**                  Direction                              : <Automatic>
**                  FTM channel 1                          : <Automatic>
**                  Direction                              : <Automatic>
**                  FTM external clock input               : <Automatic>
**                  FTM fault input 0                      : <Automatic>
**                  FTM quadrature decoder phase A input   : <Automatic>
**                  FTM quadrature decoder phase B input   : <Automatic>
**                  FTM trigger input 0                    : <Automatic>
**                  FTM trigger input 1                    : <Automatic>
**                  FTM trigger input 2                    : <Automatic>
**                Bool_FTM2                                : yes
**              Peripheral Type GPIO                       : 
**                Custom name                              : GPIOA
**                GPIOA                                    : 
**                  General purpose IO pin 0               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 1               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 2               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 3               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 4               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 18              : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 19              : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 20              : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_GPIOA                               : yes
**                Custom name                              : GPIOB
**                GPIOB                                    : 
**                  General purpose IO pin 0               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 1               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 2               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 3               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 16              : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 17              : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_GPIOB                               : yes
**                Custom name                              : GPIOC
**                GPIOC                                    : 
**                  General purpose IO pin 0               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 1               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 2               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 3               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 4               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 5               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 6               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 7               : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_GPIOC                               : yes
**                Custom name                              : GPIOD
**                GPIOD                                    : 
**                  General purpose IO pin 0               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 1               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 2               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 3               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 4               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 5               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 6               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 7               : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_GPIOD                               : yes
**                Custom name                              : GPIOE
**                GPIOE                                    : 
**                  General purpose IO pin 16              : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 17              : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 18              : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 19              : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 20              : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 21              : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 24              : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 25              : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 29              : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 30              : ADC1_SE4/CMP0_IN4/CMP1_IN4/DAC0_OUT/PTE30/FTM0_CH3/FTM_CLKIN1
**                  Direction                              : Output
**                Bool_GPIOE                               : yes
**              Peripheral Type I2C                        : 
**                Custom name                              : I2C0
**                I2C0                                     : 
**                  I2C Serial Clock Line                  : <Automatic>
**                  I2C Serial Data Line                   : <Automatic>
**                Bool_I2C0                                : yes
**              Peripheral Type LLWU                       : 
**                Custom name                              : LLWU
**                LLWU                                     : 
**                  Low-leakage wake-up                    : <Automatic>
**                  Low-leakage wake-up                    : <Automatic>
**                  Low-leakage wake-up                    : <Automatic>
**                  Low-leakage wake-up                    : <Automatic>
**                  Low-leakage wake-up                    : <Automatic>
**                  Low-leakage wake-up                    : <Automatic>
**                  Low-leakage wake-up                    : <Automatic>
**                  Low-leakage wake-up                    : <Automatic>
**                  Low-leakage wake-up                    : <Automatic>
**                  Low-leakage wake-up                    : <Automatic>
**                  Low-leakage wake-up                    : <Automatic>
**                Bool_LLWU                                : yes
**              Peripheral Type LPTMR                      : 
**                Custom name                              : LPTMR0
**                LPTMR0                                   : 
**                  LPTMR pulse counter input 1            : <Automatic>
**                  LPTMR pulse counter input 2            : <Automatic>
**                  LPTMR pulse counter input 3            : <Automatic>
**                Bool_LPTMR0                              : yes
**              Peripheral Type MCG                        : 
**                Custom name                              : MCG
**              Peripheral Type MCM                        : 
**                Custom name                              : MCM
**              Peripheral Type MMDVSQ                     : 
**                Custom name                              : MMDVSQ
**              Peripheral Type MTB                        : 
**              Peripheral Type MTBDWT                     : 
**              Peripheral Type NV                         : 
**                Custom name                              : FTFA_FlashConfig
**              Peripheral Type NVIC                       : 
**                Custom name                              : NVIC
**              Peripheral Type OSC                        : 
**                Custom name                              : OSC0
**                OSC0                                     : 
**                  Oscillator 0 input                     : <Automatic>
**                  Oscillator 0 output                    : <Automatic>
**                Bool_OSC0                                : yes
**              Peripheral Type PDB                        : 
**                Custom name                              : PDB0
**                PDB0                                     : 
**                  Trigger input 0                        : <Automatic>
**                Bool_PDB0                                : yes
**              Peripheral Type PMC                        : 
**                Custom name                              : PMC
**                PMC                                      : 
**                  MCU power supply                       : VDD1
**                  MCU power supply                       : VDD22
**                  MCU ground                             : VSS2
**                  MCU ground                             : VSS23
**                Bool_PMC                                 : yes
**              Peripheral Type PORT                       : 
**                Custom name                              : PORTA
**                Custom name                              : PORTB
**                Custom name                              : PORTC
**                Custom name                              : PORTD
**                Custom name                              : PORTE
**              Peripheral Type RCM                        : 
**                Custom name                              : RCM
**                RCM                                      : 
**                  Reset input                            : <Automatic>
**                Bool_RCM                                 : yes
**              Peripheral Type ROM                        : 
**              Peripheral Type SCB                        : 
**                Custom name                              : SystemControl
**                SystemControl                            : 
**                  Non-maskable interrupt request pin     : <Automatic>
**                Bool_SystemControl                       : yes
**              Peripheral Type SIM                        : 
**                Custom name                              : SIM
**                SIM                                      : 
**                  Clock generation SIM output 0          : <Automatic>
**                  FTM0 channel 0 modulated with carrier output: <Automatic>
**                  FTM0 channel 1 modulated with carrier output: <Automatic>
**                  FTM0 channel 2 modulated with carrier output: <Automatic>
**                  FTM0 channel 3 modulated with carrier output: <Automatic>
**                  FTM0 channel 4 modulated with carrier output: <Automatic>
**                  FTM0 channel 5 modulated with carrier output: <Automatic>
**                  FTM2 channel 0 modulated with carrier output: <Automatic>
**                  FTM2 channel 1 modulated with carrier output: <Automatic>
**                  SIM XOR input FTM1 channel 1           : <Automatic>
**                  SIM XOR input FTM2 channel 0           : <Automatic>
**                  SIM XOR input FTM2 channel 1           : <Automatic>
**                  UART0 transmit data modulated with FTM channel 0 output: <Automatic>
**                  UART1 transmit data modulated with FTM channel 0 output: <Automatic>
**                Bool_SIM                                 : yes
**              Peripheral Type SMC                        : 
**                Custom name                              : SMC
**              Peripheral Type SPI                        : 
**                Custom name                              : SPI0
**                SPI0                                     : 
**                  SPI peripheral chip select 0           : <Automatic>
**                  Direction                              : <Automatic>
**                  SPI peripheral chip select 1           : <Automatic>
**                  SPI peripheral chip select 2           : <Automatic>
**                  SPI peripheral chip select 3           : <Automatic>
**                  SPI peripheral chip select 4           : <Automatic>
**                  SPI serial data in                     : <Automatic>
**                  SPI serial clock                       : <Automatic>
**                  Direction                              : <Automatic>
**                  SPI serial data out                    : <Automatic>
**                Bool_SPI0                                : yes
**              Peripheral Type SysTick                    : 
**                Custom name                              : SysTick
**              Peripheral Type UART                       : 
**                Custom name                              : UART0
**                UART0                                    : 
**                  UART clear to send                     : <Automatic>
**                  UART request to send                   : <Automatic>
**                  UART receive data                      : <Automatic>
**                  UART transmit data                     : <Automatic>
**                Bool_UART0                               : yes
**                Custom name                              : UART1
**                UART1                                    : 
**                  UART clear to send                     : <Automatic>
**                  UART request to send                   : <Automatic>
**                  UART receive data                      : <Automatic>
**                  UART transmit data                     : <Automatic>
**                Bool_UART1                               : yes
**              Peripheral Type WDOG                       : 
**                Custom name                              : WDOG
**              Non-peripheral pins                        : 
**            Electrical properties                        : 
**              Pin 1: VDD1                                : 
**                Custom name, Signal name                 : VDD1
**              Pin 2: VSS2                                : 
**                Custom name, Signal name                 : VSS2
**              Pin 3: ADC0_SE1/ADC0_DP1/ADC1_SE0/PTE16/SPI0_PCS0/SS_b/UART1_TX/FTM_CLKIN0/FTM0_FLT3: 
**                Custom name, Signal name                 : ADC0_SE1/ADC0_DP1/ADC1_SE0/PTE16/SPI0_PCS0/SS_b/UART1_TX/FTM_CLKIN0/FTM0_FLT3
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 4: ADC0_SE5/ADC0_DM1/ADC1_SE5/PTE17/SPI0_SCK/UART1_RX/FTM_CLKIN1/LPTMR0_ALT3: 
**                Custom name, Signal name                 : ADC0_SE5/ADC0_DM1/ADC1_SE5/PTE17/SPI0_SCK/UART1_RX/FTM_CLKIN1/LPTMR0_ALT3
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 5: ADC0_SE6/ADC1_SE1/ADC1_DP1/PTE18/SPI0_SOUT/UART1_CTS_b/I2C0_SDA/SPI0_SIN: 
**                Custom name, Signal name                 : ADC0_SE6/ADC1_SE1/ADC1_DP1/PTE18/SPI0_SOUT/UART1_CTS_b/I2C0_SDA/SPI0_SIN
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 6: ADC0_SE7/ADC1_SE7/ADC1_DM1/PTE19/SPI0_SIN/UART1_RTS_b/I2C0_SCL/SPI0_SOUT: 
**                Custom name, Signal name                 : ADC0_SE7/ADC1_SE7/ADC1_DM1/PTE19/SPI0_SIN/UART1_RTS_b/I2C0_SCL/SPI0_SOUT
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 7: ADC0_SE0/ADC0_DP0/PTE20/FTM1_CH0/UART0_TX: 
**                Custom name, Signal name                 : ADC0_SE0/ADC0_DP0/PTE20/FTM1_CH0/UART0_TX
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 8: ADC0_SE4/ADC0_DM0/PTE21/FTM1_CH1/UART0_RX: 
**                Custom name, Signal name                 : ADC0_SE4/ADC0_DM0/PTE21/FTM1_CH1/UART0_RX
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 9: VDDA                                : 
**                Custom name, Signal name                 : VDDA
**              Pin 10: VREFH                              : 
**                Custom name, Signal name                 : VREFH
**              Pin 11: VREFL                              : 
**                Custom name, Signal name                 : VREFL
**              Pin 12: VSSA                               : 
**                Custom name, Signal name                 : VSSA
**              Pin 13: CMP1_IN5/CMP0_IN5/PTE29/FTM0_CH2/FTM_CLKIN0: 
**                Custom name, Signal name                 : CMP1_IN5/CMP0_IN5/PTE29/FTM0_CH2/FTM_CLKIN0
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 14: ADC1_SE4/CMP0_IN4/CMP1_IN4/DAC0_OUT/PTE30/FTM0_CH3/FTM_CLKIN1: 
**                Custom name, Signal name                 : ADC1_SE4/CMP0_IN4/CMP1_IN4/DAC0_OUT/PTE30/FTM0_CH3/FTM_CLKIN1
**                Slew rate                                : <Automatic>
**                Open drain                               : Disabled
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : Enabled
**              Pin 15: PTE24/FTM0_CH0/I2C0_SCL/EWM_OUT_b  : 
**                Custom name, Signal name                 : PTE24/FTM0_CH0/I2C0_SCL/EWM_OUT_b
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 16: PTE25/FTM0_CH1/I2C0_SDA/EWM_IN     : 
**                Custom name, Signal name                 : PTE25/FTM0_CH1/I2C0_SDA/EWM_IN
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 17: PTA0/UART0_CTS_b/FTM0_CH5/SWD_CLK  : 
**                Custom name, Signal name                 : PTA0/UART0_CTS_b/FTM0_CH5/SWD_CLK
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 18: PTA1/UART0_RX/FTM2_CH0/CMP0_OUT/FTM2_QD_PHA/FTM1_CH1: 
**                Custom name, Signal name                 : PTA1/UART0_RX/FTM2_CH0/CMP0_OUT/FTM2_QD_PHA/FTM1_CH1
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 19: PTA2/UART0_TX/FTM2_CH1/CMP1_OUT/FTM2_QD_PHB/FTM1_CH0: 
**                Custom name, Signal name                 : PTA2/UART0_TX/FTM2_CH1/CMP1_OUT/FTM2_QD_PHB/FTM1_CH0
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 20: PTA3/UART0_RTS_b/FTM0_CH0/FTM2_FLT0/EWM_OUT_b/SWD_DIO: 
**                Custom name, Signal name                 : PTA3/UART0_RTS_b/FTM0_CH0/FTM2_FLT0/EWM_OUT_b/SWD_DIO
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 21: PTA4/LLWU_P3/FTM0_CH1/FTM0_FLT3/NMI_b: 
**                Custom name, Signal name                 : PTA4/LLWU_P3/FTM0_CH1/FTM0_FLT3/NMI_b
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 22: VDD22                              : 
**                Custom name, Signal name                 : VDD22
**              Pin 23: VSS23                              : 
**                Custom name, Signal name                 : VSS23
**              Pin 24: EXTAL0/PTA18/FTM0_FLT2/FTM_CLKIN0  : 
**                Custom name, Signal name                 : EXTAL0/PTA18/FTM0_FLT2/FTM_CLKIN0
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 25: XTAL0/PTA19/FTM0_FLT0/FTM1_FLT0/FTM_CLKIN1/LPTMR0_ALT1: 
**                Custom name, Signal name                 : XTAL0/PTA19/FTM0_FLT0/FTM1_FLT0/FTM_CLKIN1/LPTMR0_ALT1
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 26: PTA20/RESET_b                      : 
**                Custom name, Signal name                 : PTA20/RESET_b
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 27: ADC0_SE8/ADC1_SE8/PTB0/LLWU_P5/I2C0_SCL/FTM1_CH0/FTM1_QD_PHA/UART0_RX: 
**                Custom name, Signal name                 : ADC0_SE8/ADC1_SE8/PTB0/LLWU_P5/I2C0_SCL/FTM1_CH0/FTM1_QD_PHA/UART0_RX
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 28: ADC0_SE9/ADC1_SE9/PTB1/I2C0_SDA/FTM1_CH1/FTM0_FLT2/EWM_IN/FTM1_QD_PHB/UART0_TX: 
**                Custom name, Signal name                 : ADC0_SE9/ADC1_SE9/PTB1/I2C0_SDA/FTM1_CH1/FTM0_FLT2/EWM_IN/FTM1_QD_PHB/UART0_TX
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 29: ADC0_SE10/ADC1_SE10/ADC1_DM2/PTB2/I2C0_SCL/UART0_RTS_b/FTM0_FLT1/FTM0_FLT3: 
**                Custom name, Signal name                 : ADC0_SE10/ADC1_SE10/ADC1_DM2/PTB2/I2C0_SCL/UART0_RTS_b/FTM0_FLT1/FTM0_FLT3
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 30: ADC1_SE2/ADC1_DP2/PTB3/I2C0_SDA/UART0_CTS_b/FTM0_FLT0: 
**                Custom name, Signal name                 : ADC1_SE2/ADC1_DP2/PTB3/I2C0_SDA/UART0_CTS_b/FTM0_FLT0
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 31: PTB16/UART0_RX/FTM_CLKIN2/EWM_IN   : 
**                Custom name, Signal name                 : PTB16/UART0_RX/FTM_CLKIN2/EWM_IN
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 32: PTB17/UART0_TX/FTM_CLKIN1/EWM_OUT_b: 
**                Custom name, Signal name                 : PTB17/UART0_TX/FTM_CLKIN1/EWM_OUT_b
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 33: ADC1_SE11/PTC0/SPI0_PCS4/PDB0_EXTRG/CMP0_OUT/FTM0_FLT0/SPI0_PCS0/SS_b: 
**                Custom name, Signal name                 : ADC1_SE11/PTC0/SPI0_PCS4/PDB0_EXTRG/CMP0_OUT/FTM0_FLT0/SPI0_PCS0/SS_b
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 34: ADC1_SE3/PTC1/LLWU_P6/SPI0_PCS3/UART1_RTS_b/FTM0_CH0/FTM2_CH0: 
**                Custom name, Signal name                 : ADC1_SE3/PTC1/LLWU_P6/SPI0_PCS3/UART1_RTS_b/FTM0_CH0/FTM2_CH0
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 35: ADC0_SE11/CMP1_IN0/PTC2/SPI0_PCS2/UART1_CTS_b/FTM0_CH1/FTM2_CH1: 
**                Custom name, Signal name                 : ADC0_SE11/CMP1_IN0/PTC2/SPI0_PCS2/UART1_CTS_b/FTM0_CH1/FTM2_CH1
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 36: CMP1_IN1/PTC3/LLWU_P7/SPI0_PCS1/UART1_RX/FTM0_CH2/CLKOUT: 
**                Custom name, Signal name                 : CMP1_IN1/PTC3/LLWU_P7/SPI0_PCS1/UART1_RX/FTM0_CH2/CLKOUT
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 37: PTC4/LLWU_P8/SPI0_PCS0/SS_b/UART1_TX/FTM0_CH3/CMP1_OUT: 
**                Custom name, Signal name                 : PTC4/LLWU_P8/SPI0_PCS0/SS_b/UART1_TX/FTM0_CH3/CMP1_OUT
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 38: PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/CMP0_OUT/FTM0_CH2: 
**                Custom name, Signal name                 : PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/CMP0_OUT/FTM0_CH2
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 39: CMP0_IN0/PTC6/LLWU_P10/SPI0_SOUT/PDB0_EXTRG/UART0_RX/I2C0_SCL: 
**                Custom name, Signal name                 : CMP0_IN0/PTC6/LLWU_P10/SPI0_SOUT/PDB0_EXTRG/UART0_RX/I2C0_SCL
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 40: CMP0_IN1/PTC7/SPI0_SIN/UART0_TX/I2C0_SDA: 
**                Custom name, Signal name                 : CMP0_IN1/PTC7/SPI0_SIN/UART0_TX/I2C0_SDA
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 41: PTD0/LLWU_P12/SPI0_PCS0/SS_b/UART0_CTS_b/FTM0_CH0/UART1_RX: 
**                Custom name, Signal name                 : PTD0/LLWU_P12/SPI0_PCS0/SS_b/UART0_CTS_b/FTM0_CH0/UART1_RX
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 42: ADC0_SE2/PTD1/SPI0_SCK/UART0_RTS_b/FTM0_CH1/UART1_TX: 
**                Custom name, Signal name                 : ADC0_SE2/PTD1/SPI0_SCK/UART0_RTS_b/FTM0_CH1/UART1_TX
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 43: PTD2/LLWU_P13/SPI0_SOUT/UART0_RX/FTM0_CH2/I2C0_SCL: 
**                Custom name, Signal name                 : PTD2/LLWU_P13/SPI0_SOUT/UART0_RX/FTM0_CH2/I2C0_SCL
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 44: PTD3/SPI0_SIN/UART0_TX/FTM0_CH3/I2C0_SDA: 
**                Custom name, Signal name                 : PTD3/SPI0_SIN/UART0_TX/FTM0_CH3/I2C0_SDA
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 45: PTD4/LLWU_P14/SPI0_PCS1/UART0_RTS_b/FTM0_CH4/FTM2_CH0/EWM_IN: 
**                Custom name, Signal name                 : PTD4/LLWU_P14/SPI0_PCS1/UART0_RTS_b/FTM0_CH4/FTM2_CH0/EWM_IN
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 46: ADC0_SE3/PTD5/SPI0_PCS2/UART0_CTS_b/FTM0_CH5/FTM2_CH1/EWM_OUT_b: 
**                Custom name, Signal name                 : ADC0_SE3/PTD5/SPI0_PCS2/UART0_CTS_b/FTM0_CH5/FTM2_CH1/EWM_OUT_b
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 47: ADC1_SE6/PTD6/LLWU_P15/SPI0_PCS3/UART0_RX/FTM0_CH0/FTM1_CH0/FTM0_FLT0: 
**                Custom name, Signal name                 : ADC1_SE6/PTD6/LLWU_P15/SPI0_PCS3/UART0_RX/FTM0_CH0/FTM1_CH0/FTM0_FLT0
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 48: PTD7/UART0_TX/FTM0_CH1/FTM1_CH1/FTM0_FLT1: 
**                Custom name, Signal name                 : PTD7/UART0_TX/FTM0_CH1/FTM1_CH1/FTM0_FLT1
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**          Settings                                       : 
**            Clock gates initialization mode              : SIM HAL (fsl_sim_hal component)
**            Inherited HAL components                     : 
**              fsl_port_hal                               : fsl_port_hal
**              fsl_sim_hal                                : fsl_sim_hal
**              fsl_mcg_hal                                : fsl_mcg_hal
**     Contents    :
**         hardware_init               - void hardware_init(void);
**         init_coredebug_pins         - void init_coredebug_pins(uint32_t instance);
**         deinit_coredebug_pins       - void deinit_coredebug_pins(uint32_t instance);
**         init_gpio_pins              - void init_gpio_pins(uint32_t instance);
**         deinit_gpio_pins            - void deinit_gpio_pins(uint32_t instance);
**         init_llwu_pins              - void init_llwu_pins(uint32_t instance);
**         deinit_llwu_pins            - void deinit_llwu_pins(uint32_t instance);
**         init_rcm_pins               - void init_rcm_pins(uint32_t instance);
**         deinit_rcm_pins             - void deinit_rcm_pins(uint32_t instance);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file pin_mux.h
** @version 1.4
** @brief
**
*/         
/*!
**  @addtogroup pin_mux_module pin_mux module documentation
**  @{
*/         

#ifndef pin_mux_H_
#define pin_mux_H_

/* MODULE pin_mux. */


/*!
 * @brief ADC method sets registers according routing settings. Call
 *         this method code to route desired pins into:
 *         ADC0, ADC1
 *         peripherals.
 * @param instance - ADC instance number 0..1
 */
void init_adc_pins(uint32_t instance);
/*!
 * @brief ADC method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for:
 *         ADC0, ADC1
 *         peripherals.
 * @param instance - ADC instance number 0..1
 */
void deinit_adc_pins(uint32_t instance);
/*!
 * @brief CMP method sets registers according routing settings. Call
 *         this method code to route desired pins into:
 *         CMP0, CMP1
 *         peripherals.
 * @param instance - CMP instance number 0..1
 */
void init_cmp_pins(uint32_t instance);
/*!
 * @brief CMP method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for:
 *         CMP0, CMP1
 *         peripherals.
 * @param instance - CMP instance number 0..1
 */
void deinit_cmp_pins(uint32_t instance);
/*!
 * @brief CoreDebug method sets registers according routing settings. Call
 *         this method code to route desired pins into CoreDebug periphery.
 * @param instance - CoreDebug instance number (0 is expected)
 */
void init_coredebug_pins(uint32_t instance);
/*!
 * @brief CoreDebug method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for CoreDebug periphery.
 * @param instance - CoreDebug instance number (0 is expected)
 */
void deinit_coredebug_pins(uint32_t instance);
/*!
 * @brief DAC method sets registers according routing settings. Call
 *         this method code to route desired pins into DAC0 periphery.
 * @param instance - DAC instance number (0 is expected)
 */
void init_dac_pins(uint32_t instance);
/*!
 * @brief DAC method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for DAC0 periphery.
 * @param instance - DAC instance number (0 is expected)
 */
void deinit_dac_pins(uint32_t instance);
/*!
 * @brief DMA method sets registers according routing settings. Call
 *         this method code to route desired pins into DMA periphery.
 * @param instance - DMA instance number (0 is expected)
 */
void init_dma_pins(uint32_t instance);
/*!
 * @brief DMA method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for DMA periphery.
 * @param instance - DMA instance number (0 is expected)
 */
void deinit_dma_pins(uint32_t instance);
/*!
 * @brief EWM method sets registers according routing settings. Call
 *         this method code to route desired pins into EWM periphery.
 * @param instance - EWM instance number (0 is expected)
 */
void init_ewm_pins(uint32_t instance);
/*!
 * @brief EWM method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for EWM periphery.
 * @param instance - EWM instance number (0 is expected)
 */
void deinit_ewm_pins(uint32_t instance);
/*!
 * @brief FTM method sets registers according routing settings. Call
 *         this method code to route desired pins into:
 *         FTM0, FTM1, FTM2
 *         peripherals.
 * @param instance - FTM instance number 0..2
 */
void init_ftm_pins(uint32_t instance);
/*!
 * @brief FTM method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for:
 *         FTM0, FTM1, FTM2
 *         peripherals.
 * @param instance - FTM instance number 0..2
 */
void deinit_ftm_pins(uint32_t instance);
/*!
 * @brief GPIO method sets registers according routing settings. Call
 *         this method code to route desired pins into:
 *         GPIOA, GPIOB, GPIOC, GPIOD, GPIOE
 *         peripherals.
 * @param instance - GPIO instance number 0..4
 */
void init_gpio_pins(uint32_t instance);
/*!
 * @brief GPIO method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for:
 *         GPIOA, GPIOB, GPIOC, GPIOD, GPIOE
 *         peripherals.
 * @param instance - GPIO instance number 0..4
 */
void deinit_gpio_pins(uint32_t instance);
/*!
 * @brief I2C method sets registers according routing settings. Call
 *         this method code to route desired pins into I2C0 periphery.
 * @param instance - I2C instance number (0 is expected)
 */
void init_i2c_pins(uint32_t instance);
/*!
 * @brief I2C method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for I2C0 periphery.
 * @param instance - I2C instance number (0 is expected)
 */
void deinit_i2c_pins(uint32_t instance);
/*!
 * @brief LLWU method sets registers according routing settings. Call
 *         this method code to route desired pins into LLWU periphery.
 * @param instance - LLWU instance number (0 is expected)
 */
void init_llwu_pins(uint32_t instance);
/*!
 * @brief LLWU method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for LLWU periphery.
 * @param instance - LLWU instance number (0 is expected)
 */
void deinit_llwu_pins(uint32_t instance);
/*!
 * @brief LPTMR method sets registers according routing settings. Call
 *         this method code to route desired pins into LPTMR0 periphery.
 * @param instance - LPTMR instance number (0 is expected)
 */
void init_lptmr_pins(uint32_t instance);
/*!
 * @brief LPTMR method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for LPTMR0 periphery.
 * @param instance - LPTMR instance number (0 is expected)
 */
void deinit_lptmr_pins(uint32_t instance);
/*!
 * @brief OSC method sets registers according routing settings. Call
 *         this method code to route desired pins into OSC0 periphery.
 * @param instance - OSC instance number (0 is expected)
 */
void init_osc_pins(uint32_t instance);
/*!
 * @brief OSC method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for OSC0 periphery.
 * @param instance - OSC instance number (0 is expected)
 */
void deinit_osc_pins(uint32_t instance);
/*!
 * @brief PDB method sets registers according routing settings. Call
 *         this method code to route desired pins into PDB0 periphery.
 * @param instance - PDB instance number (0 is expected)
 */
void init_pdb_pins(uint32_t instance);
/*!
 * @brief PDB method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for PDB0 periphery.
 * @param instance - PDB instance number (0 is expected)
 */
void deinit_pdb_pins(uint32_t instance);
/*!
 * @brief PMC method sets registers according routing settings. Call
 *         this method code to route desired pins into PMC periphery.
 * @param instance - PMC instance number (0 is expected)
 */
void init_pmc_pins(uint32_t instance);
/*!
 * @brief PMC method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for PMC periphery.
 * @param instance - PMC instance number (0 is expected)
 */
void deinit_pmc_pins(uint32_t instance);
/*!
 * @brief RCM method sets registers according routing settings. Call
 *         this method code to route desired pins into RCM periphery.
 * @param instance - RCM instance number (0 is expected)
 */
void init_rcm_pins(uint32_t instance);
/*!
 * @brief RCM method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for RCM periphery.
 * @param instance - RCM instance number (0 is expected)
 */
void deinit_rcm_pins(uint32_t instance);
/*!
 * @brief SCB method sets registers according routing settings. Call
 *         this method code to route desired pins into SystemControl periphery.
 * @param instance - SCB instance number (0 is expected)
 */
void init_scb_pins(uint32_t instance);
/*!
 * @brief SCB method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for SystemControl periphery.
 * @param instance - SCB instance number (0 is expected)
 */
void deinit_scb_pins(uint32_t instance);
/*!
 * @brief SIM method sets registers according routing settings. Call
 *         this method code to route desired pins into SIM periphery.
 * @param instance - SIM instance number (0 is expected)
 */
void init_sim_pins(uint32_t instance);
/*!
 * @brief SIM method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for SIM periphery.
 * @param instance - SIM instance number (0 is expected)
 */
void deinit_sim_pins(uint32_t instance);
/*!
 * @brief SPI method sets registers according routing settings. Call
 *         this method code to route desired pins into SPI0 periphery.
 * @param instance - SPI instance number (0 is expected)
 */
void init_spi_pins(uint32_t instance);
/*!
 * @brief SPI method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for SPI0 periphery.
 * @param instance - SPI instance number (0 is expected)
 */
void deinit_spi_pins(uint32_t instance);
/*!
 * @brief UART method sets registers according routing settings. Call
 *         this method code to route desired pins into:
 *         UART0, UART1
 *         peripherals.
 * @param instance - UART instance number 0..1
 */
void init_uart_pins(uint32_t instance);
/*!
 * @brief UART method sets registers according routing settings. Call
 *         this method code to disable routing of desired pins for:
 *         UART0, UART1
 *         peripherals.
 * @param instance - UART instance number 0..1
 */
void deinit_uart_pins(uint32_t instance);


/* END pin_mux. */
#endif /* #ifndef __pin_mux_H_ */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
